### ISSUE TITLE
TypeError: Cannot read property 'loadLocales' of undefined

### ISSUE THREAD

**Issue by r8420** [sr229/monika#10]
![image](https://user-images.githubusercontent.com/26418513/35035830-c60545f6-fb72-11e7-99f7-6741d24b44cd.png)

**Comment by sr229** [comment]
Thanks for reporting, I fixed this issue via a commit, sorry if this hurdled at any point.

**Comment by r8420** [comment]
Thank you for fixing that issue. But now I get another error:
![image](https://user-images.githubusercontent.com/26418513/35046568-aa86ff48-fb97-11e7-8e2a-e588a7560717.png)
Cannot read property 'locales' of undefined

**Comment by sr229** [comment]
@r8420 thanks again! I think this was something I simply overlooked during the porting process.
