### ISSUE TITLE
TypeError: bot.getGuildSettings is not a function

### ISSUE THREAD

**Issue by r8420** [sr229/monika#11]
When I send a command (?help) to the bot in discord it doesn't respond and this error is in the log:
**You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TypeError: bot.getGuildSettings is not a function**
![image](https://user-images.githubusercontent.com/26418513/35062741-6ce3bdc4-fbc5-11e7-8d59-a9cfab65ea37.png)

log says that the bot is started:
![image](https://user-images.githubusercontent.com/26418513/35062882-c71c73ee-fbc5-11e7-9f0d-18f2000aab53.png)
Bot also doesn't have a status on discord

**Comment by sr229** [comment]
thanks for reporting the issue, I think I've triaged this to two event handlers. Should be an easy fix

**Comment by sr229** [comment]
I institiuted a fix on ``sr229/dev``, will close this on a merge once I've confirmed it's good
